name: sosmap
description: Flutter firebase auth example.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: any
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  another_flushbar: ^1.10.20

  cupertino_icons: ^1.0.2
  location: ^2.5.4
  weather_icons: ^2.0.1
  connectivity: ^0.4.8+1
  fluttertoast: ^3.1.0
  flutter_speed_dial: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  wemapgl:
    #git: https://github.com/WEMAP-Official/WeMap-Flutter-SDK.git
    path: ../WeMapSDK
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/symbols/custom-icon.png
    - assets/symbols/help.png
    - assets/symbols/origin.png
    - assets/symbols/destination.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/2.0x/help.png
    - assets/symbols/2.0x/origin.png
    - assets/symbols/2.0x/destination.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/symbols/3.0x/help.png
    - assets/symbols/3.0x/origin.png
    - assets/symbols/3.0x/destination.png
    - assets/geojson/ne_10m_ports.geojson
    - assets/geojson/line-samples.geojson
    - assets/geojson/polygon-samples.geojson
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/email_icon.png
    - assets/images/password_icon.png
    - assets/images/user_icon.png
    - assets/images/as.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
